# Generated by Django 3.0.6 on 2020-05-31 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist', '0002_auto_20200531_1605'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='imdbid',
            new_name='imdbID',
        ),
    ]
