# Generated by Django 3.0.6 on 2020-06-03 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist', '0006_movie_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='slug',
        ),
    ]
